---
- name: Transferring files
  hosts: ginodb1
  gather_facts: no

  tasks:
    - name: 1. Deleting the old file named '.profile' on the remote host.
      file:
        state: absent
        path: /oracle12c/upgrade/main/.profile
      become: yes

    - name: 2. Uploading the new file named '.profile' to the remote host.
      copy:
        src: /ansible/data/.profile
        dest: /oracle12c/upgrade/main/
        owner: oracle
        group: dba
        mode: 0755
      become: yes

    - name: 3. Verify the new file named '.profile' is uploaded.
      shell: "ls -la /oracle12c/upgrade/main/ | grep '.profile' "
      register: file_Verification
      become: yes
    - debug: var=file_Verification.stdout_lines